<Project>

  <!-- Shared settings for all projects in the solution. -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <PlatformTarget>x64</PlatformTarget>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

</Project>